package dev.catac.check;

public enum SkipReason {
    NOT_APPLICABLE,
    EXEMPT,
    SYNCHRONIZING,
    WORLD_UNAVAILABLE,
    UNMODELED,
    INSUFFICIENT_HISTORY,
    DISCONTINUITY,
    BUDGET_EXHAUSTED,
    INTEGRATION_FAILURE,
    UNTRUSTED_STATE,
    STALE_REFERENCE,
    PROFILE_UNVALIDATED,
    SERVER_LAG
}
