package dev.catac.state;

/** Tracks the confirmation generated by Minestom's position synchronization. */
final class TeleportTracker {
    private final long timeoutNanos;
    private boolean pending;
    private boolean awaitingId;
    private int expectedId;
    private long deadlineNanos;

    TeleportTracker(long timeoutNanos) {
        this.timeoutNanos = timeoutNanos;
    }

    void markPending(long nowNanos) {
        pending = true;
        awaitingId = true;
        deadlineNanos = nowNanos + timeoutNanos;
    }

    void captureExpectedId(int teleportId) {
        if (pending && awaitingId && teleportId >= 0) {
            expectedId = teleportId;
            awaitingId = false;
        }
    }

    boolean acknowledge(int teleportId, long nowNanos) {
        if (!pending || awaitingId || nowNanos > deadlineNanos || teleportId != expectedId) {
            return false;
        }
        pending = false;
        return true;
    }

    boolean pending(long nowNanos) {
        if (pending && nowNanos > deadlineNanos) {
            pending = false;
        }
        return pending;
    }
}
